//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeOptionsFacility
    {
        public int RoomTypeOptionsFacilityID { get; set; }
        public int RoomTypeOptionID { get; set; }
        public int OfficeFacilityID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual OfficeFacility OfficeFacility { get; set; }
        public virtual RoomTypeOption RoomTypeOption { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
