//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypeOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomTypeOption()
        {
            this.Rooms = new HashSet<Room>();
            this.RoomTypeOptionsFacilities = new HashSet<RoomTypeOptionsFacility>();
        }
    
        public int RoomTypeOptionID { get; set; }
        public int RoomTypeID { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> IsRefundable { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomTypeOptionsFacility> RoomTypeOptionsFacilities { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual User User1 { get; set; }
    }
}
